
var maleNameArray = new Array();
var femaleNameArray = new Array();

maleNameArray = [
'Arl',	'Barak',	'Atellus',	'Alaric',	'Able',
'Bruul',	'Cain',	'Brutis',	'Attilas',	'Bones',
'Dar',	'Dariel',	'Callidon',	'Barbosa',	'Crisis',
'Frak',	'Eli',	'Castus',	'Cortez',	'Cutter',
'Fral',	'Enoch',	'Drustos',	'Constantine',	'Dekko',
'Garm',	'Frastus',	'Flavion',	'Cromwell',	'Dakka',
'Grish',	'Gaius',	'Gallus',	'Dorn',	'Frag',
'Grak',	'Garvel',	'Haxtes',	'Drake',	'Flair',
'Hak',	'Hastus',	'Intios',	'Eisen',	'Finial',
'Jarr',	'Ignace',	'Jastilus',	'Ferrus',	'Grim',
'Kar',	'Ishmael',	'Kaltos',	'Grendel',	'Gob',
'Karrl',	'Jericus',	'Litilus',	'Gulilliman',	'Gunner',
'Krell',	'Klightus',	'Lupus',	'Havelock',	'Hack',
'Lek',	'Lazerus',	'Mallear',	'Iacton', 'Jakes',
'Mar',	'Mordeci',	'Metalus',	'Jaghatai',	'Krak',
'Mir',	'Mithras',	'Nihilius',	'Khan',	'Lug',
'Narl',	'Nicodemus',	'Novus',	'Leman',	'Mongrel',
'Orl',	'Pontius',	'Octus',	'Lionus',	'Plex',
'Phrenz',	'Quint',	'Praetus',	'Magnus',	'Rat',
'Quarl',	'Rabalias',	'Quintos',	'Mercutio',	'Red',
'Roth',	'Reestheus',	'Raltus',	'Nixios',	'Sawney',
'Ragaa',	'Silvanus',	'Ravion',	'Ramirez',	'Scab',
'Stig',	'Solomon',	'Regis',	'Serghar',	'Scammer',
'Strang',	'Thaddius',	'Severus',	'Sigismund',	'Skive',
'Thak',	'Titus',	'Silon',	'Tybalt',	'Shanks',
'Ulth',	'Uriah',	'Tauron',	'Vern',	'Shiv',
'Varn', 'Varnias',	'Trantor',	'Wolfe',	'Sham',
'Wrax',	'Xerxes',	'Venris',	'Wollsey',	'Stern',
'Yarn',	'Zaddion',	'Victus',	'Zane',	'Stubber',
'Zek',	'Zuriel',	'Xanthis',	'Zarkov',	'Verbal',
'Arz', 'Aaz', 'Azararch', 'Barik', 'Canto',
'Baranoth', 'Bones', 'Carm', 'Darrial', 'Castess',
'Caradoc', 'Farn', 'Davrus', 'Draco', 'Garak',
'Festus', 'Erioch', 'Eizen', 'Dokk', 'Horst',
'Galliach', 'Ferris', 'Ergs', 'Imk', 'Harlon',
'Harthos', 'Grendal', 'Fanz', 'Jart', 'Irlven',
'Icharus', 'Harlocke', 'Kulem', 'Jaspar', 'Karpath',
'Jenquin', 'Garrit', 'Larl', 'Killian', 'Lothos',
'Karlos', 'Hons', 'Mok', 'Lazarus', 'Marius',
'Lemant', 'Ills', 'Mordicai', 'Noctine', 'Jaq',
'Oort', 'Octavius', 'Naveen', 'Lax', 'Pak',
'Quinten', 'Partheos', 'Oscarl', 'Meng', 'Rhaban',
'Quellus', 'Perrin', 'Nast', 'Salc', 'Silvanto',
'Ramalies', 'Romulus', 'Reddin', 'Tarl', 'Severan',
'Sabanth', 'Volc', 'Tyruss', 'Urial', 'Yarl',
'Ventium', 'Tranq', 'Zel', 'Zariel', 'Zarath', 'Wurm'];

femaleNameArray = [
'Arla',	'Akadia',	'Atella',	'Aenid',	'Alpha',
'Brulla',	'Chaldia',	'Brutilla',	'Albia',	'Blaze',
'Darl',	'Cyrine',	'Callidia',	'Borgia',	'Blue',
'Fraka',	'Diona',	'Castella',	'Cimbria',	'Cat',
'Fraal',	'Deatrix',	'Drustilla',	'Devil',	'Calamity',
'Garma',	'Ethina',	'Flavia',	'Ephese',	'Dame',
'Grisha',	'Ephrael',	'Gallia',	'Euphrati',	'Dice',
'Graki',	'Fenria',	'Haxta',	'Inez',	'Flair',
'Haka',	'Gaia',	'Intias',	'Imperatrice',	'Gold',
'Jarra',	'Galatia',	'Jestilla',	'Jemadar',	'Gunner',
'Karna',	'Hazael',	'Kalta',	'Jezail',	'Hack',
'Kaarli',	'Isha',	'Litila',	'Joss',	'Halo',
'Krella',	'Ishta',	'Lupa',	'Kadis',	'Lady',
'Lekka',	'Jedia',	'Mallia',	'Kali',	'Luck',
'Marlla',	'Judicca',	'Meta',	'Lethe',	'Modesty',
'Mira',	'Lyra',	'Nihila',	'Mae',	'Moll',
'Narla',	'Magdela',	'Novia',	'Millicent',	'Pistol',
'Orla',	'Narcia',	'Octia',	'Merica',	'Plex',
'Phrix',	'Ophilia',	'Praetia',	'Midkiff',	'Pris',
'Quali',	'Phebia',	'Quintilla',	'Megehra',	'Rat',
'Rotha',	'Qualia',	'Raltia',	'Odessa',	'Red',
'Ragaana',	'Rhia',	'Ravia',	'Orlean',	'Ruby',
'Stigga',	'Salomis',	'Regia',	'Plath',	'Scarlet',
'Stranga',	'Solaris',	'Scythia',	'Severine',	'Spike',
'Thakka',	'Thyratia',	'Sila',	'Thiopia',	'Steel',
'Ultha',	'Thebe',	'Taura',	'Thrace',	'Starr',
'Varna',	'Uriel',	'Trantia',	'Tzarine',	'Trauma',
'Wraxa',	'Veyda',	'Venria',	'Venus',	'Trick',
'Yarni',	'Xantippe',	'Xanthia',	'Walperga',	'Trix',
'Zekka',	'Ziapatra',	'Zethina',	'Zetkin',	'Zee',
'Arda', 'Acadi', 'Araleen', 'Aennisse', 'Alta',
'Cil', 'Balida', 'Bianca', 'Dara', 'Cassa',
'Elleantra', 'Drusilla', 'Echo', 'Elphet',
'Darial', 'Fausta', 'Eos', 'Fatal', 'Frakka',
'Frennine', 'Florenza', 'Flame', 'Heras',
'Genevieve', 'Gamma', 'Halli', 'Hannette',
'Irissa', 'Grace', 'Ing', 'Jinzia', 'Jucinda',
'Jocasta', 'Jaine', 'Julla', 'Karroleen', 'Lucindia',
'Katarina', 'Lho', 'Kelle', 'Liri', 'Mycandra',
'Mini', 'Merra', 'Magdala', 'Novianna', 'Miranda',
'Nerva', 'Nimm', 'Nuella', 'Pollonia', 'Newt',
'Nulla', 'Pennette', 'Palanza', 'Rosalind', 'Paz',
'Quineel', 'Praenta', 'Russa', 'Tessera', 'Sulle',
'Sesselie', 'Tzarelle', 'Thima', 'Thesse', 'Temetria',
'Urania', 'Tanda', 'Vas', 'Uri', 'Thallia', 'Verity',
'Yanne', 'Xandra', 'Wynnif', 'Xina', 'Zanna', 'Zadori',
'Yemmise', 'Yasta','Zedda'];
